### PR TITLE
Minimal 2.10 version

### PR DESCRIPTION
**Pull request by adriaanm**
Winging it for the 2.10.5 release....

### CODE REVIEW

**Comment by TestingBlocking** [comment]
this is Seth, testing. ignore

**Comment by TestingBlocking** [comment]
testing again

**Comment by TestingBlocking** [comment]
testing 3

**Comment by TestingBlocking** [comment]
testing 4

**Comment by TestingBlocking** [comment]
testing 5

**Comment by adriaanm** [comment]
I dare you to comment again.

**Pull request merged**
