### PR TITLE
fix version number format to be Scala Steward friendly

### LINKED ISSUE #45: Scala Steward not working in this repo?
on Discord, @tgodzik says

> Hey all, it seems that there are a couple of repositories that are currently failing in the public Scala Steward instance. I tried making a list here https://github.com/VirtusLab/scala-steward-repos/issues/98 though I wasn't able to go through everything myself and I am a bit low on time to do it. If your repository is on the list and you are missing updates do let me know. I can try to send you some debug information and we can try to figure it out together. Alternatively, you can set up a separate local Scala Steward and debug it yourself.

and for this repo in particular,

> it seems we are getting:

```
java.io.IOException: 'sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
[info] welcome to sbt 1.7.1 (Eclipse Adoptium Java 11.0.16.1)
[info] loading global plugins from /root/.sbt/1.0/plugins
[info] compiling 1 Scala source to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] done compiling
[info] loading settings for project scala-dist-smoketest-build from plugins.sbt ...
[info] loading project definition from /opt/workspace/repos/scala/scala-dist-smoketest/project
[info] loading settings for project scala-dist-smoketest from build.sbt ...
[info] set current project to scala-dist-smoketest (in build file:/opt/workspace/repos/scala/scala-dist-smoketest/)
java.lang.IllegalArgumentException: Invalid comparator: 4faeb905e70fc36cd3b00d25d756400050efaa07
    at sbt.internal.librarymanagement.SemComparatorFunctions.parse(SemanticSelectorExtra.scala:208)
    at sbt.internal.librarymanagement.SemComparator$.apply(SemComparator.scala:54)
    at sbt.internal.librarymanagement.SemSelAndChunkFunctions.$anonfun$parse$2(SemanticSelectorExtra.scala:14)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
    at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
    at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
```

> though that was a while ago when I downloaded the logs, but might be the same issue

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #45

### CODE REVIEW

**Comment by SethTisue** [comment]
if I understand correctly, it's expected that PR validation fails:

> [error] sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-library:2.11.4-93-72f0796b

because it isn't doing `export version=2.13.11-bin-d193135 scala_sha=d1931352941e5cca75c6afec1813192ec4283775` or similar before running

so I'm going to go ahead and merge this, and I'll be sure and check the next nightly run to make sure everything is still ok

**Comment by SethTisue** [comment]
hmm, this also regressed the merge build. that's not okay. I'll send a followup PR

**Comment by SethTisue** [comment]
d5afcba8c65b9e1f8fb6a54777d2acce59d4405d straight up reverts this while I consider my next move

**Comment by SethTisue** [comment]
instead: #47

**Comment by som-snytt** [comment]
also the issue should be labeled `friendliness`.

**Pull request merged**
